# -*- coding: utf-8 -*-
"""Read_mail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UMinm0bckwUcp8VeEfbVm5nZaR4BsVVF
"""

import smtplib
import time
import imaplib
import email

# here we define basic variables which we need
ORG_EMAIL   = "@gmail.com"
FROM_EMAIL  = "nikhilkhicherplb" + ORG_EMAIL
FROM_PWD    = "nkbisnoi1299"
SMTP_SERVER = "imap.gmail.com"
SMTP_PORT   = 993

# define function for reading mail
def read_mail():
    mail=imaplib.IMAP4_SSL(SMTP_SERVER)
    mail.login(FROM_EMAIL,FROM_PWD) # login
    mail.select('inbox') # select which type of mail we read
    type,data=mail.search(None,'ALL')
    mail_ids=data[0]
    id_list=mail_ids.split() # split all mail_ids
    first_mail_id=int(id_list[0])
    last_mail_id=int(id_list[-1])
    
    # fetch mails
    for i in range(last_mail_id,first_mail_id,-1):
      typ, dat = mail.fetch(i, '(RFC822)' )
      
      for response_part in data:
                if isinstance(response_part, tuple):
                    msg = email.message_from_string(response_part[1])
                    email_subject = msg['subject']
                    email_from = msg['from']
                    print( 'From : ' + email_from + '\n') # print sender mail
                    print ('Subject : ' + email_subject + '\n') # subject

read_mail()

